services:
  yellosolarhubserver:
    image: yellosolarhubserver
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
