# Yarn Berry (v3+) Configuration
# Ref: https://yarnpkg.com/configuration/yarnrc

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

# Default npm registry
npmRegistryServer: "https://registry.yarnpkg.com"
