version: "3.8"

services:
  postgres-test:
    image: postgres:16-alpine
    container_name: ysh-b2b-postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_DB: medusa_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432" # Use different port to avoid conflicts
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - ysh-b2b-test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d medusa_test"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  redis-test:
    image: redis:7-alpine
    container_name: ysh-b2b-redis-test
    restart: unless-stopped
    ports:
      - "6380:6379" # Use different port to avoid conflicts
    volumes:
      - redis_test_data:/data
    networks:
      - ysh-b2b-test-network
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

volumes:
  postgres_test_data:
    driver: local
  redis_test_data:
    driver: local

networks:
  ysh-b2b-test-network:
    driver: bridge
